name: Build Production
on:
  push:
    branches: [main]
    paths-ignore:
      - 'web/**'

permissions:
  contents: read
  id-token: write

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.1
          cache: true
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: |
          mkdir release
          dart run msix:create
          cp build/windows/x64/runner/Release/ExifHelper.msix release/ExifHelper.msix
          dart run msix:create -d Exif小助手 -n Exif小助手
          cp build/windows/x64/runner/Release/Exif小助手.msix release/Exif小助手.msix
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path:
            ${{ github.workspace }}/release
  
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev -y
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.1
          cache: true
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build linux
      - name: Compress
        run: tar release.tar.gz build/linux/x64/release/bundle   
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: release.tar.gz    
  
  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.1
          cache: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-android-sdk
          path: |
            ~/.android/build-cache
            ~/.android/sdk
      - name: Set up SDK
        uses: android-actions/setup-android@v3
      - name: Set up Keystore
        uses: timheuer/base64-to-file@v1
        with:
          encodedString: ${{secrets.KEY_STORE_FILE}}
          fileName: keystore.jks
          fileDir: android/app
      - name: Set up Environment Variables
        run: |
          echo "storeFile=keystore.jks" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
      - name: Build
        run: flutter build apk --split-per-abi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/*.apk
